run:
  timeout: 10m
  modules-download-mode: vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 10
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen:
    lines: 60
    statements: 40
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  nestif:
    min-complexity: 5
  lll:
    line-length: 120

linters:
  # Отключаем ТОЛЬКО проблемные и deprecated линтеры
  disable:
    - asciicheck
    - execinquery
    - exhaustivestruct
    - exportloopref
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
  
  # Включаем ВСЕ остальные линтеры
  enable-all: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - goconst
        - dupl
        - gocognit
    - path: vendor/
      linters:
        - all
    - text: "TODO"
      linters:
        - godox
    - text: "FIXME"
      linters:
        - godox

severity:
  default: error