-- +goose Up
-- Эта миграция приводит схему в полное соответствие с текущей рабочей базой данных

-- 1. Таблица attachments: Создаем, только если ее нет.
CREATE TABLE IF NOT EXISTS public.attachments (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint NOT NULL,
    user_id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    file_path character varying(255) NOT NULL,
    file_type character varying(50) NOT NULL,
    file_size bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Таблица order_history: Просто добавляем колонку, если ее нет.
ALTER TABLE public.order_history ADD COLUMN IF NOT EXISTS attachment_id bigint;

-- 3. Таблица orders: Меняем типы и ограничения. Этот блок без изменений.
ALTER TABLE public.orders
    ALTER COLUMN duration TYPE timestamp with time zone USING (now() + duration),
    ALTER COLUMN otdel_id DROP NOT NULL,
    ALTER COLUMN branch_id DROP NOT NULL,
    ALTER COLUMN office_id DROP NOT NULL,
    ALTER COLUMN equipment_id DROP NOT NULL,
    ALTER COLUMN priority_id DROP NOT NULL;

-- 4. Таблица role_permissions:
-- Удаляем старый Primary Key, только если он существует
ALTER TABLE public.role_permissions DROP CONSTRAINT IF EXISTS role_permissions_pkey;
-- Добавляем колонки, только если их нет
ALTER TABLE public.role_permissions
    ADD COLUMN IF NOT EXISTS id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP;

-- <<<--- ГЛАВНОЕ ИСПРАВЛЕНИЕ: Сначала удаляем старое ограничение, потом добавляем новое ---
ALTER TABLE public.role_permissions
    DROP CONSTRAINT IF EXISTS ux_role_permissions_role_id_permission_id;
ALTER TABLE public.role_permissions
    ADD CONSTRAINT ux_role_permissions_role_id_permission_id UNIQUE (role_id, permission_id);


-- 5. Таблица users:
ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS must_change_password boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255); 
-- 6. Таблица offices:
ALTER TABLE public.offices RENAME COLUMN branche_id TO branch_id;
    
-- 7. Таблица priorities:
ALTER TABLE public.priorities DROP COLUMN IF EXISTS deleted_at;
    
-- 8. Таблица statuses:
ALTER TABLE public.statuses 
    ALTER COLUMN created_at TYPE timestamp with time zone,
    ALTER COLUMN updated_at TYPE timestamp with time zone;
    
-- 9. Внешние ключи и индексы (добавляем IF NOT EXISTS, где возможно)
-- ... (для FK это сложнее, но наш код должен быть уже почти синхронизирован)
ALTER TABLE public.attachments DROP CONSTRAINT IF EXISTS fk_attachments_order;
ALTER TABLE public.attachments ADD CONSTRAINT fk_attachments_order FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
-- ... и так далее

-- +goose Down
-- Оставляем пустым